# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p04-reid-master' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p04-reid-master
	pod 'Charts'

end
